### ISSUE TITLE
3rd party libedit/editline --> incorrectly displays unicode chars

### ISSUE THREAD

**Issue by stsauver** [farsightsec/axa#2]
Summary: sratool shows incorrectly represented Unicode/wide characters when built with
external libedit/editline

Details:  Some systems need a 3rd party libedit/editline library to build axa. This would 
normally come from http://thrysoee.dk/editline/

Note the lined out comment there:

    "Unicode
    To build libedit with support for unicode (wide-char/UTF-8), add
    the --enable-widec option when running configure,

    ./configure --enable-widec"

That lined out text was replaced with:

    "Always builds with unicode (wide-char/UTF-8) support now."

Reproduce Issue: Once axa is built from sources and installed with the
quoted libedit/editline library, start sratool, type a random non-command 
and hit return:

sratool
sra> asdasdasdasasdadsd
unrecognized command "asdasdasdasasdadsd"
 ?
sra> \U+C473\U+C461\U+C464\U+C461\U+C473\U+C464

Note unrendered wide characters.

Jeremy noted in email:

-- quote --
Maybe because the code uses char but when using wide char it should be  
wchar_t.

I see some other projects like asterisk and LLDB had same problem with  
the editline upgrade, for example:
https://github.com/asterisk/asterisk/commit/72da2ef9ffb49a1fc550ec91caa1468e285f87e0
http://llvm.org/viewvc/llvm-project?revision=303907&view=revision
I can look at reproducing this and provide a ifdef for this in axa 
(maybe in sratool/cmd.c). [...]

(By the way, the change came from NetBSD.)
-- quote --

Thanks,

Joe

**Comment by reedjc** [comment]
I reproduced this. Its behavior was a little different. Even when I type at the prompt I received the Unicode output at the same time. When I pressed Enter it showed U+F780A for example.

**Comment by reedjc** [comment]
This was fixed in the upstream version. The commit message there:

   add libedit wchar (Unicode) support

  libedit as of 3.11 decided to force Unicode support by changing the callback signature of the `getcfn` (`el_rfunc_t`) callback from a `char *` to a `wchar_t *`. We handle that by reading a wchar and converting to a char. Note this patch does not port AXA to support Unicode, only to correctly handle editline/readline library variants vis-a-vis Unicode/`getcfn`.
